project:
  type: website
  output-dir: docs

website:
  title: "Learning Azure Governance"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - topics.qmd
  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - topics.qmd        
        - text: "---"
        - topics/cost-and-accounting.qmd
        - text: "---"       
        - topics/new-development-project.qmd       
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
