!include https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist/AzureCommon.puml

'java -jar "C:\Program Files\PlantUML\plantuml.jar" -encodesprite 16z -tpng excel_48px.png
sprite $Excel [48x48/8] {
________________zzzzzzjjjjjj____________________
______zzzzzjjjjjjjjiiiiiaajj____________________
zjjjjjjiiiiiiaaaaaaaaaaaaajj____________________
jjaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjj
jjaaaaaaaaaaaaaaaaaaaaaaaajj000000000000000000jj
jjaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjb00bjjjjjjb00jj
jjaaaaaaaaaaaaaaaaaaaaaaaajjjjjjji00ijjjjjji00jj
jjaaaaaaaaaaaaaaaaaaaaaaaajj000000000000000000jj
jjaaaaaa00YaaaaY00aaaaaaaajjjjjjjb00bjjjjjjb00jj
jjaaaaaaK00YaaY00Kaaaaaaaajjjjjjji00ijjjjjji00jk
jjaaaaaaaK00YY00Kaaaaaaaaajj000000000000000000ks
jjaaaaaaaaK0000Kaaaaaaaaaajjjjjjjb00bjjjkskc00ss
jjaaaaaaaaaI00Iaaaaaaaaaaajjjjjjji00ijjjrssq00ss
jjaaaaaaaaY0000Yaaaaaaaaaajj000000000000000000ss
jjaaaaaaaY00KK00Yaaaaaaaaajjjjjjjb00bjjssssc00ss
jjaaaaaaY00KaaK00Yaaaaaaaajjjjjjji00ijsssssq00ss
jjaaaaaa00KaaaaK01aaaaaaaajj000000000000000000ss
jjaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjb00cssssssc00ss
jjaaaaaaaaaaaaaaaaaaaaaaaajjjjjjji00qssssssq00ss
jjaaaaaaaaaaaaaaaaaaaaaaaajj000000000000000000ss
jjbaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjkssssssssss
ljjjjjjjjbbbbbaaaaaaaaaaaajj____________________
______llllljjjjjjjjjbbbbbbjj____________________
________________lllllljjjjjj____________________
}

AzureEntityColoring(Excel)
!define Excel(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, Excel, Excel)
!define Excel(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, Excel, Excel)
