---
title: "New Development Project"
---

Source: [Governance](https://github.com/MicrosoftLearning/AZ-305-DesigningMicrosoftAzureInfrastructureSolutions/blob/master/Instructions/CaseStudy/01-Governance.md)

<h2>Design a governance solution</h2>

**Requirements**

Tailwind Traders is planning on making some significant changes to their governance solution. They have asked for your assistance with recommendations and questions. Here are the specific requirements.

New development project. The company has a new development project for customer feedback. The CFO wants to ensure all costs associated with the project are captured. For the testing phase, workloads should be hosted on lower cost virtual machines. The virtual machines should be named to indicate they are part of the project. Any instances of non-compliance with resource consistency rules should be automatically identified.

**Tasks**

- What are the different ways Tailwind Traders could track costs for the new development project?

- How are you ensuring compliance with the requirements for virtual machine sizing and naming?

- Propose at least two ways of meeting the requirements. Explain your final decision.

How are you incorporating the [Well Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/) pillars to produce a high quality, stable, and efficient cloud architecture?

|Pillar|Description|
|--|--|
|[Reliability](https://learn.microsoft.com/en-us/azure/well-architected/resiliency/)|The ability of a system to recover from failures and continue to function.|
|[Security](https://learn.microsoft.com/en-us/azure/well-architected/security/)|Protecting applications and data from threats.|
|[Cost Optimization](https://learn.microsoft.com/en-us/azure/well-architected/cost/)|Managing costs to maximize the value delivered.|
|[Operational Excellence](https://learn.microsoft.com/en-us/azure/well-architected/devops/)|Operations processes that keep a system running in production.|
|[Performance Efficiency](https://learn.microsoft.com/en-us/azure/well-architected/scalability/)|The ability of a system to adapt to changes in load.|
