!include https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist/AzureCommon.puml

sprite $Sharepoint [54x54/16z] {
dPQBUiCW28Kzg8ZGzt_UHPimajehlVaj_1vqW2AbqnlxToAghMiD3wBZeu4AIpUpsyrgMXly1mcK1w0wY65MVUeWWoXGkMt4xkzKY0X1QGf4u4mjBTUw0VO0
B2FqiKJ_ZxNwxHr508PKVB-ZK5XQ1ivx-8wYDdvxFktXXzHDgrEVH4Xo7mc583_Lkcb9RfzJnZ4tFgI663tHic7BTGsCuVaOAEl2cubUjDmQSFqlMwDZAbbH
Dh5BX0RulZPxYB3dF0OCn0Yj3W2KSy911QsMaVBcQkKKeOuvSkkgNQe42harBZGVwwR96VyHoXZptLljL5z4aza6mrTxomTbCjUpgXHFT6BTjxeU4KwgY3sl
Igh-K6cdZ0P6hBRk07CptEenvhqCkDjQguI_TvyX7tNAjbeNECRmhzjezo1TH8WQ88rvA0NtOFGI8LOHkkdWaAWlgB0RnfVwwZEpv4nXVbNpcB1JNbOoFDgg
YnBRiP0ZevJr_jl6pBBAgEGPXV_SA3DrEMC-ZjahhGmEPPszeBdvOBtMLo_0lL9EzINXXCswwg9bU3A5-ehBpisMtSOxGEmsPbrQ4-ch7kKxZiVJmTlQkaVf
4TutNRHN-g9ZopxYUC9-ggLr4C1tVLxoDoUiTz5VJjY2zCr9XCojZTpxweHD02XTxm3Dtb0k4WUvL9QkzjNTPhQ9NCgBszVgDkd2Zjg9YfunqlX6tj3JhT8r
BewFTrCgjSKRR9GuZ_0GVYxSUpq_E6J_
}

AzureEntityColoring(Sharepoint)
!define Sharepoint(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, Sharepoint, Sharepoint)
!define Sharepoint(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, Sharepoint, Sharepoint)
